name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Chọn phiên bản Node.js phù hợp
          cache: "npm"

      - name: Install dependencies
        run: npm install  # Hoặc yarn install nếu dùng yarn

      - name: Build project with Vite
        run: npm run build:client  # Chạy "vite build --config vite.client.config.ts"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client-dist  # Thư mục build output của Vite

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
